markdown: kramdown
title: "PHash Blog"
description: "perceptual hashing information"
theme: jekyll-theme-modernist
repository_url: starkdg/starkdg.github.io
permalink: /posts/:title
email: starkd88@gmail.com
show_downloads: false
